### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AngrySwarmOfBees** [salaxieb/perlin_noise#2]
I would like to create 3 or 4 dimensional Perlin noise using this package, I am struggling to understand the way that the math works, could you please provide information on how your package works and its functions?

**Comment by salaxieb** [comment]
for using this library in 3 or 4 dimensions you don't really have to know math behind
```from perlin_noise import PerlinNoise
noise = PerlinNoise()
noise([0.5, 0.1, 0.4, 5, 0, 323])
----> some value in [-1, 1]
```
if you want to have intuition behind, let me explain in simplest example with octaves=1 and 1D request
1. at each integer in line we initialize vectors perpendicular to our line with random length [-1, 1]
2. for each coordinate, we request, use only 2 neighbour integers i.e. vectors
3. value at each coordinate between those 2 vectors (v1 and v2) is equal to 
`weight(v1) * gradient(v1) + weight(v2) * gradient(v2)`
      where weight equal to absolute distance between coordinate and integer
      gradient is length of vector
 (so that's why you will get 0 at each integer point, because there is no weight)
4. apply some fade function which further smoothes values
ex:  `val = 6*val^5 - 15*val^4 + 10*val^3`

with this intuition you can figure out that for 2 dimensional request 4 corner vectors will be used, for 3 dimensional 8 vectors and so on

octaves regulate how often put those vectors,  ex.: 
octaves = 1 means put them at each integer
octaves = 10 meant to put 10 vectors between each integer

**Comment by AngrySwarmOfBees** [comment]
okay, so if I understand this correctly- 
`pic = [[[noise([i/xpix, j/ypix,k/zpix]) for j in range(xpix)] for i in range(ypix)] for i in range zpix]`
would work for 3 dimensions?
I'm so sorry if I'm wasting your time, and thank you for your help-

**Comment by salaxieb** [comment]
yes, it will
```
from perlin_noise import PerlinNoise

noise = PerlinNoise()
xpix, ypix, zpix = 10, 10, 10
pic = [[[noise([i/xpix, j/ypix, k/zpix]) for j in range(xpix)] for i in range(ypix)] for k in range(zpix)]
```

**Comment by AngrySwarmOfBees** [comment]
Oh, okay that makes sense, I was making it more complicated than it should have been-
Thank you for taking the time to help me figure this out.
